server:
  servlet:
    encoding:
      force-response: true
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heartDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: urstory
    password: u1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mustache:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: /static/**

file:
  upload:
    directory: C:\Users\T16\Desktop\playdata\project\RepoHeart\heart\build\resources\main\static\uploads

    